services:
  - type: web
    name: house-price-predictor
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"  # or main:app depending on your file name
    envVars:
      - key: PORT
        value: 10000
